version: '3'

services:
#   db-pg-blog-user:
#     image: 'bitnami/postgresql:latest'
#     environment:
#       POSTGRESQL_PASSWORD: ${DB_DEFAULT_PASSWORD}
#       POSTGRESQL_USERNAME: ${DB_DEFAULT_USERNAME}
#       POSTGRESQL_DATABASE: ${DB_DEFAULT_DATABASE}
#       POSTGRESQL_TIMEZONE: America/SAO_PAULO
#     ports:
#       - "${DB_DEFAULT_PORT}:${DB_DEFAULT_PORT}"
#     restart: unless-stopped
#     container_name: db-pg-blog-user
#     networks:
#       - kong-net
#     volumes:
#       - ./pgdata:/var/lib/postgresql/data

  blog-user:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: blog-user:latest
    environment:
      DB_DEFAULT_PASSWORD: ${DB_DEFAULT_PASSWORD}
      DB_DEFAULT_USERNAME: ${DB_DEFAULT_USERNAME}
      DB_DEFAULT_DATABASE: ${DB_DEFAULT_DATABASE}
      DB_DEFAULT_TYPE: ${DB_DEFAULT_TYPE}
      DB_DEFAULT_HOST: ${DB_DEFAULT_HOST}
      DB_DEFAULT_PORT: ${DB_DEFAULT_PORT}
      API_PORT: ${API_PORT}
      NODE_ENV: ${NODE_ENV}
      SENTRY_DSN: ${SENTRY_DSN}
    ports:
      - "${API_PORT}:${API_PORT}"
    container_name: blog-user
    # depends_on:
    #   - db-pg-blog-user
    networks:
      - kong-net
    volumes:
      - .:/app
      - /app/node_modules

# volumes:
#   pgdata:


networks:
  kong-net:
    external: true
