version: '3'

services:
  blog-user:
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: ./entrypoint.sh
    container_name: blog-user
    image: blog-user:latest
    environment:
      SONAR_PROJECT_KEY: ${SONAR_PROJECT_KEY}
      SONAR_SERVER_URL: ${SONAR_SERVER_URL}
      VALIDATION_LOGIN_ATTEMPTS_TRY_LIMIT: ${VALIDATION_LOGIN_ATTEMPTS_TRY_LIMIT}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      JWT_SECRET: ${JWT_SECRET}
      SONAR_PASSWORD: ${SONAR_PASSWORD}
      SONAR_LOGIN: ${SONAR_LOGIN}
      BLOG_USER_SENTRY_DSN: ${BLOG_USER_SENTRY_DSN}
      DB_DEFAULT_DATABASE: ${DB_DEFAULT_DATABASE}
      DB_DEFAULT_PASSWORD: ${DB_DEFAULT_PASSWORD}
      DB_DEFAULT_USERNAME: ${DB_DEFAULT_USERNAME}
      DB_DEFAULT_PORT: ${DB_DEFAULT_PORT}
      DB_DEFAULT_HOST: ${DB_DEFAULT_HOST}
      DB_DEFAULT_TYPE: ${DB_DEFAULT_TYPE}
      BLOG_USER_PORT: ${BLOG_USER_PORT}
      NODE_ENV: ${NODE_ENV}
      URL_BASE_DATA_REPLICATION: ${URL_BASE_DATA_REPLICATION}
      URL_BASE_NOTIFICATION: ${URL_BASE_NOTIFICATION}
    ports:
      - "${BLOG_USER_PORT}:${BLOG_USER_PORT}"
    networks:
      - blog-net
    volumes:
      - .:/home/node/app/blog-user

networks:
  blog-net:
    external: true
